########################################################
#         For github.com/sevcator/zapret-pocket        #
########################################################

listen_addresses = ['127.0.0.1:5253']

server_names = ['google']

max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = true
require_dnssec = true
require_nolog = false
require_nofilter = true
disabled_server_names = []

force_tcp = false
http3 = true
timeout = 8000
keepalive = 60

use_syslog = false

cert_refresh_delay = 240
bootstrap_resolvers = ['8.8.8.8:53', '8.8.4.4:53']
ignore_system_dns = true
netprobe_timeout = 10
netprobe_address = '8.8.4.4:53'

block_ipv6 = true
block_unqualified = false
block_undelegated = true
reject_ttl = 10

cache = true
cache_size = 1024
cache_min_ttl = 300
cache_max_ttl = 7200
cache_neg_min_ttl = 30
cache_neg_max_ttl = 180

cloaking_rules = 'cloaking-rules.txt'

[blocked_names]
blocked_names_file = 'blocked-names.txt'

[blocked_ips]
blocked_ips_file = 'blocked-ips.txt'

[broken_implementations]
fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cisco-sandbox', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']

[anonymized_dns]
skip_incompatible = true

[static]
[static.'google']
stamp = 'sdns://AgUAAAAAAAAABzguOC44LjggsKKKE4EwvtIbNjGjagI2607EdKSVHowYZtyvD9iPrkkHOC44LjguOAovZG5zLXF1ZXJ5'
